const paises = [
  {descripcion: 'Afganistán'},
  {descripcion: 'Albania'},
  {descripcion: 'Alemania'},
  {descripcion: 'Andorra'},
  {descripcion: 'Angola'},
  {descripcion: 'Antigua y Barbuda'},
  {descripcion: 'Arabia Saudita'},
  {descripcion: 'Argelia'},
  {descripcion: 'Argentina'},
  {descripcion: 'Armenia'},
  {descripcion: 'Australia'},
  {descripcion: 'Austria'},
  {descripcion: 'Azerbaiyán'},
  {descripcion: 'Bahamas'},
  {descripcion: 'Bangladés'},
  {descripcion: 'Barbados'},
  {descripcion: 'Baréin'},
  {descripcion: 'Bélgica'},
  {descripcion: 'Belice'},
  {descripcion: 'Benín'},
  {descripcion: 'Bielorrusia'},
  {descripcion: 'Birmania'},
  {descripcion: 'Bolivia'},
  {descripcion: 'Bosnia y Herzegovina'},
  {descripcion: 'Botsuana'},
  {descripcion: 'Brasil'},
  {descripcion: 'Brunéi'},
  {descripcion: 'Bulgaria'},
  {descripcion: 'Burkina Faso'},
  {descripcion: 'Burundi'},
  {descripcion: 'Bután'},
  {descripcion: 'Cabo Verde'},
  {descripcion: 'Camboya'},
  {descripcion: 'Camerún'},
  {descripcion: 'Canadá'},
  {descripcion: 'Catar'},
  {descripcion: 'Chad'},
  {descripcion: 'Chile'},
  {descripcion: 'China'},
  {descripcion: 'Chipre'},
  {descripcion: 'Ciudad del Vaticano'},
  {descripcion: 'Colombia'},
  {descripcion: 'Comoras'},
  {descripcion: 'Corea del Norte'},
  {descripcion: 'Corea del Sur'},
  {descripcion: 'Costa de Marfil'},
  {descripcion: 'Costa Rica'},
  {descripcion: 'Croacia'},
  {descripcion: 'Cuba'},
  {descripcion: 'Dinamarca'},
  {descripcion: 'Dominica'},
  {descripcion: 'Ecuador'},
  {descripcion: 'Egipto'},
  {descripcion: 'El Salvador'},
  {descripcion: 'Emiratos Árabes Unidos'},
  {descripcion: 'Eritrea'},
  {descripcion: 'Eslovaquia'},
  {descripcion: 'Eslovenia'},
  {descripcion: 'España'},
  {descripcion: 'Estados Unidos'},
  {descripcion: 'Estonia'},
  {descripcion: 'Etiopía'},
  {descripcion: 'Filipinas'},
  {descripcion: 'Finlandia'},
  {descripcion: 'Fiyi'},
  {descripcion: 'Francia'},
  {descripcion: 'Gabón'},
  {descripcion: 'Gambia'},
  {descripcion: 'Georgia'},
  {descripcion: 'Ghana'},
  {descripcion: 'Granada'},
  {descripcion: 'Grecia'},
  {descripcion: 'Guatemala'},
  {descripcion: 'Guyana'},
  {descripcion: 'Guinea'},
  {descripcion: 'Guinea ecuatorial'},
  {descripcion: 'Guinea-Bisáu'},
  {descripcion: 'Haití'},
  {descripcion: 'Honduras'},
  {descripcion: 'Hungría'},
  {descripcion: 'India'},
  {descripcion: 'Indonesia'},
  {descripcion: 'Irak'},
  {descripcion: 'Irán'},
  {descripcion: 'Irlanda'},
  {descripcion: 'Islandia'},
  {descripcion: 'Islas Marshall'},
  {descripcion: 'Islas Salomón'},
  {descripcion: 'Israel'},
  {descripcion: 'Italia'},
  {descripcion: 'Jamaica'},
  {descripcion: 'Japón'},
  {descripcion: 'Jordania'},
  {descripcion: 'Kazajistán'},
  {descripcion: 'Kenia'},
  {descripcion: 'Kirguistán'},
  {descripcion: 'Kiribati'},
  {descripcion: 'Kuwait'},
  {descripcion: 'Laos'},
  {descripcion: 'Lesoto'},
  {descripcion: 'Letonia'},
  {descripcion: 'Líbano'},
  {descripcion: 'Liberia'},
  {descripcion: 'Libia'},
  {descripcion: 'Liechtenstein'},
  {descripcion: 'Lituania'},
  {descripcion: 'Luxemburgo'},
  {descripcion: 'Madagascar'},
  {descripcion: 'Malasia'},
  {descripcion: 'Malaui'},
  {descripcion: 'Maldivas'},
  {descripcion: 'Malí'},
  {descripcion: 'Malta'},
  {descripcion: 'Marruecos'},
  {descripcion: 'Mauricio'},
  {descripcion: 'Mauritania'},
  {descripcion: 'México'},
  {descripcion: 'Micronesia'},
  {descripcion: 'Moldavia'},
  {descripcion: 'Mónaco'},
  {descripcion: 'Mongolia'},
  {descripcion: 'Montenegro'},
  {descripcion: 'Mozambique'},
  {descripcion: 'Namibia'},
  {descripcion: 'Nauru'},
  {descripcion: 'Nepal'},
  {descripcion: 'Nicaragua'},
  {descripcion: 'Níger'},
  {descripcion: 'Nigeria'},
  {descripcion: 'Noruega'},
  {descripcion: 'Nueva Zelanda'},
  {descripcion: 'Omán'},
  {descripcion: 'Países Bajos'},
  {descripcion: 'Pakistán'},
  {descripcion: 'Palaos'},
  {descripcion: 'Panamá'},
  {descripcion: 'Papúa Nueva Guinea'},
  {descripcion: 'Paraguay'},
  {descripcion: 'Perú'},
  {descripcion: 'Polonia'},
  {descripcion: 'Portugal'},
  {descripcion: 'Reino Unido'},
  {descripcion: 'República Centroafricana'},
  {descripcion: 'República Checa'},
  {descripcion: 'República de Macedonia'},
  {descripcion: 'República del Congo'},
  {descripcion: 'República Democrática del Congo'},
  {descripcion: 'República Dominicana'},
  {descripcion: 'República Sudafricana'},
  {descripcion: 'Ruanda'},
  {descripcion: 'Rumanía'},
  {descripcion: 'Rusia'},
  {descripcion: 'Samoa'},
  {descripcion: 'San Cristóbal y Nieves'},
  {descripcion: 'San Marino'},
  {descripcion: 'San Vicente y las Granadinas'},
  {descripcion: 'Santa Lucía'},
  {descripcion: 'Santo Tomé y Príncipe'},
  {descripcion: 'Senegal'},
  {descripcion: 'Serbia'},
  {descripcion: 'Seychelles'},
  {descripcion: 'Sierra Leona'},
  {descripcion: 'Singapur'},
  {descripcion: 'Siria'},
  {descripcion: 'Somalia'},
  {descripcion: 'Sri Lanka'},
  {descripcion: 'Suazilandia'},
  {descripcion: 'Sudán'},
  {descripcion: 'Sudán del Sur'},
  {descripcion: 'Suecia'},
  {descripcion: 'Suiza'},
  {descripcion: 'Surinam'},
  {descripcion: 'Tailandia'},
  {descripcion: 'Tanzania'},
  {descripcion: 'Tayikistán'},
  {descripcion: 'Timor Oriental'},
  {descripcion: 'Togo'},
  {descripcion: 'Tonga'},
  {descripcion: 'Trinidad y Tobago'},
  {descripcion: 'Túnez'},
  {descripcion: 'Turkmenistán'},
  {descripcion: 'Turquía'},
  {descripcion: 'Tuvalu'},
  {descripcion: 'Ucrania'},
  {descripcion: 'Uganda'},
  {descripcion: 'Uruguay'},
  {descripcion: 'Uzbekistán'},
  {descripcion: 'Vanuatu'},
  {descripcion: 'Venezuela'},
  {descripcion: 'Vietnam'},
  {descripcion: 'Yemen'},
  {descripcion: 'Yibuti'},
  {descripcion: 'Zambia'},
  {descripcion: 'Zimbabue'},
];

module.exports = {
     paises
}